stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - artifacts/data/raw
  
  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - src/model_architecture.py
      - artifacts/data/raw
    outs:
      - artifacts/model/